### ISSUE TITLE
Needs compilation step

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/element-ready#1]
browserify automatically [skips transforms](http://stackoverflow.com/a/32669727/288906) (babel) on external modules so arrow functions are imported as is and don't work in Safari and IE.

I'd suggest rollup + rollup-buble

**Comment by bfred-it** [comment]
That doesn't really "fix" it. As is it's incompatible with all versions of Safari and breaks the entire site. Not to mention UglifyJS

**Comment by sindresorhus** [comment]
@bfred-it Not really something I care about, sorry. I made this to solve my own use-case, which is in an Electron app and a Chrome extension, both fully supporting ES2015. I've now document the requirement. There are probably other similar modules out there you can use instead ;)
