### ISSUE TITLE
MutationObserver 

### ISSUE THREAD

**Issue by zzarcon** [sindresorhus/element-ready#2]
What about using a [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) instead of an interval in order to know when the element is inserted in the dom?

I'd like to do the pr if you are ok with the feature 🚀

**Comment by vutran** [comment]
This would also enable compat for IE11 as MutationObserver is supported but not Promises.

**Comment by sindresorhus** [comment]
I considered it, but last time I tried MutationObserver, it was pretty slow. You need to watch the whole document for any changes. Happy to change if someone can prove it's faster and doesn't slow down normal page loading.

**Comment by sindresorhus** [comment]
> This would also enable compat for IE11 as MutationObserver is supported but not Promises.

It would not, as the module would still return a promise. Check out https://github.com/bfred-it/element-ready-es5

**Comment by dmitrykiselyov** [comment]
I found this plugin [Ready](https://github.com/ryanmorr/ready) that use Mutation Observers.

**Comment by sindresorhus** [comment]
Gonna close this as I still don't think MutationObserver would be better.
