### ISSUE TITLE
Subscribe to new elements on the page

### ISSUE THREAD

**Issue by fregante** [sindresorhus/element-ready#22]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/element-ready/issues/22)

elementReady only works for one element, but sometimes it’s useful to just get all the elements on the page *as they load.* For example:

```js
elementReady.subscribe('a', shortenLink);
```

This will run the function on each new element found on the page before reaching DOM ready. 

MutationObserver with `subtree:true` would be ideal for this but somewhere at some point I read that it’s heavy to run this while the page loads as there are too many events. It would be great to actually test this and compare it to a simpler `setInterval + querySelectorAll`. Without performance tests, I’d avoid MutationObserver

---

*Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Thanks for helping out 🙌*

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Submitted pull Requests
- [#24 Implement elementReady.subscribe](https://issuehunt.io/r/sindresorhus/element-ready/pull/24)
- [#36 Add `observeReadyElements`](https://issuehunt.io/r/sindresorhus/element-ready/pull/36)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/element-ready/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sindresorhus** [comment]
Should it support the same options as `elementReady()`?

**Comment by bfred-it** [comment]
I guess they’d make sense here as well

**Comment by qti3e** [comment]
I would gladly work on this if no one's working on it...

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the previous attempt and feedback in https://github.com/sindresorhus/element-ready/pull/24.

**Comment by Richienb** [comment]
What would be a good way to test the performance of `MutationObserver` vs `setInterval` + `querySelectorAll`?
