### ISSUE TITLE
Wait for an element’s contents, not just the element

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/element-ready#29]
Currently, it only wait for the exact element you target, not its children. It would be useful with an option to let you wait for the children too.

Context: https://github.com/sindresorhus/refined-github/issues/2671#issuecomment-587075136

Implementing this efficiently might not be as easy though.

**Comment by fregante** [comment]
It wouldn't only be _useful_, but I think it's something that is absolutely necessary. There's a chance that browsers might create the element before its own starting tag is complete, e.g.

```html
<a class="text-red 
```

would match `elementReady('a:not([href])')` right before the rest is loaded:


```html
<a class="text-red underline" href="./index.html">Home</a>
```

I think the expectation of an element being "ready" is that all of it is loaded, not just (part of) the opening tag.

**Comment by sindresorhus** [comment]
Are you saying this should be the default behavior without adding an option?

**Comment by fregante** [comment]
Correct, I'm saying that this is a bug (aka unexpected behavior)

**Comment by fregante** [comment]
Suggested solution, copied from the original issue:

```js
const found = querySelector();
if (found) {
	let parent = found.parentElement;
	while (parent) {
		if (parent.nextSibling) {
			resolve(found);
		}
		parent = found.parentElement;
	}
}
```

However this will fail if both of these are true:

- `found` is literally the last node on the page
- `stopOnDomReady: false`

---

Alternative solutions or PR welcome.

**Comment by fregante** [comment]
> However this will fail if both of these are true:

Actually, this whole issue only apples **before DOM ready**, since the page is being _streamed in_. This means that, once the DOM is ready, this extra check can be skipped.

This solution should work in every case:

```
const found = querySelector();
if (found) {
	if (domReady) { // This is NOT affected by `stopOnDomReady`
		resolve(found)
	}
	let parent = found.parentElement;
	while (parent) {
		if (parent.nextSibling) {
			resolve(found);
		}
		parent = found.parentElement;
	}
}
```

**Comment by sindresorhus** [comment]
Alright. Let's do it.

**Comment by fregante** [comment]
I used these changes in https://github.com/sindresorhus/refined-github/pull/3849
