### ISSUE TITLE
Include `typed-query-selector`?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/element-ready#34]
Like [I did in `select-dom`](https://github.com/fregante/select-dom/pull/15) and [intend to do in `delegate-it`,](https://github.com/fregante/delegate-it/issues/24) maybe `element-ready` could also include https://github.com/g-plane/typed-query-selector

This is probably a breaking change, so it'd be good to ship it together with ESM: https://github.com/sindresorhus/meta/discussions/15

**Comment by sindresorhus** [comment]
👍
