### ISSUE TITLE
Allow specifying a predicate function to only resolve on a more specific element

### ISSUE THREAD

**Issue by bengry** [sindresorhus/element-ready#37]
The current behavior of `elementReady` is great, but sometimes there are multiple items matching the selector. Currently, this means that the first matching element will be returned. However, there are many use-cases where other ones are wanted, and a more specific CSS selector cannot be used. For example:
```html
<ul id="country-list">
	<li>country a</li>
	...
	<li>wanted country</li>
	...
</ul>
```

Currently, you can't get the `<li>` with `wanted country`, where the entire `<ul>` (or `<li`s) is not present on the page from the get-go.

My suggestion is to add an **optional** `predicate` function to the `elementReady` options, such that you could solve the above scenario like so:
```js
const someSpecificCountry = await elementReady('#country-list > li', {
	predicate: item => !!item.textContent && /wanted country/i.test(item.textContent),
});
```

I already have a working implementation of this as a patch (using [`patch-package`](https://www.npmjs.com/package/patch-package)) and would be happy to submit a PR if this is an acceptable for the problem.

**Comment by sindresorhus** [comment]
Makes sense to me. Pull request welcome.
