### ISSUE TITLE
requestAnimationFrame instead of setInterval

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/element-ready#4]
I used element-ready for https://github.com/sindresorhus/refined-github/pull/441 but it's not fast enough. Here's a comparison with the simple [rAF-based solution](https://github.com/bfred-it/github-clean-feed/blob/a52c08473630cd911137545b16769c32e975ca5e/src/content.js#L194-L202) I used in `github-clean-feed` and how that compares with element-ready's `setInterval`

```js
const domReady = new Promise(resolve => {
	(function check() {
		if (document.querySelector('.ajax-pagination-form')) {
			resolve();
		} else {
			requestAnimationFrame(check);
		}
	})();
});
```

![reload screencast](https://cloud.githubusercontent.com/assets/1402241/26537174/a50c90f8-446f-11e7-9a7f-0b944599842f.gif)

⬆️ I'm refreshing the page. Notice the feed being instantly changed by `github-clean-feed`, but the Trending link appearing after the first paint.

`document.querySelector` is not that CPU-intensive, so running it _on every frame until domready_ is not that much to ask. Perhaps it can be an option. Either way I hope to see the change in RefinedGH

**Comment by sindresorhus** [comment]
Sure, let's go with it.
