### ISSUE TITLE
Timeout or CancelablePromise

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/element-ready#6]
I think this needs a way to stop looking for the element instead of trying ad infinitum.

Possible solutions:

```js
elementReady('.button', {timeout: 10000});

elementReady('.button', {until: require('dom-loaded')});

const ready = elementReady('.button');
gitHubInjection(window, () => ready.cancel()); // stop looking when the page changes
```

I think the CancelablePromise is the most flexible one.

**Comment by sindresorhus** [comment]
👍 `.cancel()`. Can use [`p-cancelable`](https://github.com/sindresorhus/p-cancelable).
